spring:
  h2.console:
    enabled: true
    path: '/console'


  datasource.url: 'jdbc:h2:file:./database/todo-db'
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: '*'
